name: Docker Image CI

on:
  create:
    tags: 
      - '*'
  push:
    branches: [ "2.5" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
    -
       name: Build
       run: |
          docker build -f Dockerfile -t getcarrier/observer-browsertime:2.5 .
    -
       name: Push
       run: |
         docker push getcarrier/observer-browsertime:2.5
